[0m23:19:50.421182 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106756690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062c23f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106757920>]}


============================== 23:19:50.427902 | 7cfe8f13-939f-448e-80e0-add1e3a8e42c ==============================
[0m23:19:50.427902 [info ] [MainThread]: Running with dbt=1.7.0
[0m23:19:50.429585 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/alissacheng/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:19:50.431104 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alissacheng/Documents/project-2/transform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:19:50.434414 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_wall_clock_time": 0.046757247, "process_user_time": 2.303581, "process_kernel_time": 0.39028, "process_mem_max_rss": "94019584", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m23:19:50.435512 [debug] [MainThread]: Command `dbt docs generate` failed at 23:19:50.435290 after 0.05 seconds
[0m23:19:50.436093 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062c23f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106661940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1063d8530>]}
[0m23:19:50.436672 [debug] [MainThread]: Flushing usage events
[0m16:47:49.732858 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1126095b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1124775f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1122c1370>]}


============================== 16:47:49.793421 | 97ba893f-ada2-474a-834e-727811ba167d ==============================
[0m16:47:49.793421 [info ] [MainThread]: Running with dbt=1.7.0
[0m16:47:49.794382 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/alissacheng/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt deps', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:47:49.795488 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alissacheng/Documents/project-2/transform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:47:49.807921 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.16220698, "process_user_time": 2.183436, "process_kernel_time": 0.463815, "process_mem_max_rss": "92884992", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m16:47:49.809480 [debug] [MainThread]: Command `dbt deps` failed at 16:47:49.809113 after 0.16 seconds
[0m16:47:49.810238 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1123d0fb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111455ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11260bd70>]}
[0m16:47:49.810840 [debug] [MainThread]: Flushing usage events
