[0m09:32:41.653452 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B00EB40FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B0117B4A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B0117B4820>]}


============================== 09:32:41.659421 | e0eedbe3-a1f3-432d-99cf-8948aa4b470f ==============================
[0m09:32:41.659421 [info ] [MainThread]: Running with dbt=1.7.0
[0m09:32:41.660420 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\test\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:32:41.661425 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\test\2023-12-bootcamp\09-project-2\project-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:32:41.664425 [debug] [MainThread]: Command `dbt run` failed at 09:32:41.664425 after 0.03 seconds
[0m09:32:41.665457 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B00EB40FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B0117B4820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B0117B4AF0>]}
[0m09:32:41.666785 [debug] [MainThread]: Flushing usage events
[0m20:31:30.294204 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a36e840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a0d6240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a36f920>]}


============================== 20:31:30.302490 | 4fd24b3d-1c01-443f-8e96-5f968ac8924c ==============================
[0m20:31:30.302490 [info ] [MainThread]: Running with dbt=1.7.0
[0m20:31:30.303845 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/alissacheng/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m20:31:30.305075 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alissacheng/Documents/project-2/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:31:30.317014 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.06535497, "process_user_time": 2.33013, "process_kernel_time": 0.57066, "process_mem_max_rss": "93753344", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m20:31:30.318058 [debug] [MainThread]: Command `dbt run` failed at 20:31:30.317824 after 0.07 seconds
[0m20:31:30.318709 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a0d6900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a0f4b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a259850>]}
[0m20:31:30.319481 [debug] [MainThread]: Flushing usage events
[0m18:58:48.017667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0652D34C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D067F449D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D067F44760>]}


============================== 18:58:48.022169 | 5ed60202-ded5-479b-a209-1c43ca123dfc ==============================
[0m18:58:48.022169 [info ] [MainThread]: Running with dbt=1.7.0
[0m18:58:48.023176 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\test\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:58:48.024174 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\test\2023-12-bootcamp\09-project-2\project-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:58:48.026175 [debug] [MainThread]: Command `dbt run` failed at 18:58:48.026175 after 0.02 seconds
[0m18:58:48.027173 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0652D34C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D067F44760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D067F44A30>]}
[0m18:58:48.027173 [debug] [MainThread]: Flushing usage events
